name: Test login page

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy github pages
      uses: actions/checkout@v4 
      with:
        ref: gh-pages
        path: ./.github/gh-pages
    - name: Build the Docker image
      run: | 
        docker compose -f compose.yaml up --exit-code-from test || true
    - name: Copy report history
      run: |
        sudo mkdir -p allure-results/history
        sudo cp -R ./.github/gh-pages/history/* allure-results/history/
    - name: Report
      run: | 
        sudo docker compose run test /bin/sh -c "allure generate allure-results/history --clean -o allure-report"
    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
        clean: true
