name: Test
on:
  workflow_dispatch:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test login
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci-cd/docker-compose.yml
      DOCKER_USER: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: docker-compose run 
